name: On push tag build publish release

on:
  workflow_dispatch:
    docker_tag:
      description: "Define the docker tag name. You can define the docker tag version separately"
      default: mindwendel
    docker_tag_version:
      description: "Define the docker tag version"
      required: true
  push:
    # TODO:: Remove after branch merged
    branches:
      - 44-refine-release-process-docker
    tags:
      - "*.*.*"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Setting vars for later access
        id: set_vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY_PERSONAL_ACCESS_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ format('ghcr.io/mindwendel/mindwendel_github_workflow:{0}', steps.set_vars.outputs.tag) }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
